version: '3.3'
services:
  bs_odoo150:
    image: yk2kus/odoo:bs_odoo150
    container_name: bs_odoo150
    build:
      context: .
    environment:
      - DEBIAN_FRONTEND=noninteractive
    network_mode: host
    volumes:
      - /opt/.local/share/Odoo/filestore150/:/opt/filestore
      - odoo150:/opt/odoo
#    this restart policy should be used only after image is okay, otherwise it creates huge problem
#    starting again and again not letting new changes refelect
volumes:
  odoo150:
